import Link from "next/link";
import { RitmoLogo } from "@/components/ritmo-mark";
import { EXTERNAL_NUTRITION_ENABLED } from "@/lib/nutrition/policy";
import { PRIVACY_NOTICE_VERSION } from "@/lib/privacy";

export const metadata = { title: "Tus datos y privacidad" };
export default function PrivacidadPage() {
  return <main className="mx-auto max-w-3xl px-5 py-10 sm:py-16">
    <Link href="/" aria-label="Volver a RITMO"><RitmoLogo /></Link>
    <h1 className="mt-8 font-display text-3xl font-bold">Tus datos en RITMO</h1>
    <p className="mt-3 text-muted-foreground">Información sobre cómo funciona el tratamiento de datos en la aplicación. Versión {PRIVACY_NOTICE_VERSION}.</p>
    <div className="mt-8 divide-y divide-border [&_section]:py-5 [&_h2]:mb-2 [&_h2]:text-lg [&_h2]:font-semibold [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-muted-foreground">
      <section><h2>Responsable y contacto</h2><p>El responsable de RITMO es Quique Machado, operador del proyecto publicado como <a href="https://github.com/quiquemachado5" target="_blank" rel="noopener noreferrer" className="text-primary underline underline-offset-2">quiquemachado5</a>. Puedes usar los medios de contacto de ese perfil para consultas de privacidad. No publiques peso, comidas ni otros datos de salud en una incidencia pública.</p></section>
      <section><h2>Para qué y con qué base</h2><p>El correo y la sesión permiten prestar el acceso solicitado. El perfil, hábitos, comidas, peso y medidas se usan únicamente para darte el registro, los cálculos y las predicciones de RITMO. Antes de guardar esos datos se solicita un consentimiento explícito y se conserva la fecha y versión de ese consentimiento. El diagnóstico técnico es opcional y tiene un control separado en Ajustes.</p></section>
      <section><h2>Tu cuenta y tus registros</h2><p>Supabase gestiona el acceso y almacena tu perfil, hábitos, comidas y mediciones. Las políticas de acceso separan los registros de cada cuenta. Vercel sirve la aplicación y sus funciones de servidor.</p></section>
      <section><h2>Cuando importas datos de salud</h2><p>La exportación de Apple Health o de una aplicación compatible con Health Connect se lee en tu dispositivo. RITMO no sube el archivo original: después de tu confirmación, solo sincroniza con tu cuenta las métricas seleccionadas, como peso, pasos, sueño y minutos de entrenamiento. Esta función no concede a RITMO acceso continuo a Apple Health ni a Health Connect.</p></section>
      <section><h2>Cuando analizas una comida</h2>{EXTERNAL_NUTRITION_ENABLED ? <><p>Al pulsar Analizar, se envían la descripción y las correcciones nutricionales seleccionadas al servidor. Cuando el análisis online está habilitado, puede utilizar Gemini (Google) o Edamam como alternativa. No se les envía tu correo ni tu histórico de pesajes. La pantalla identifica el origen del resultado; las cifras siguen siendo estimaciones.</p><p className="mt-2">La caché online es privada por cuenta y caduca a los diez minutos. Los registros caducados se purgan al procesar nuevas solicitudes. El tratamiento de los proveedores depende de su contrato y configuración.</p></> : <><p>El análisis se realiza en tu dispositivo con una tabla de alimentos y tus correcciones guardadas. No utiliza Gemini ni Edamam y no envía la descripción a estos servicios.</p><p className="mt-2">Es una estimación local, no una respuesta de IA. Revisa ingredientes y cantidades antes de guardar. Al registrar la comida, se sincroniza en tu cuenta como el resto de tus datos.</p></>}</section>
      <section><h2>Cuando buscas un código de barras</h2><p>Solo al pulsar Buscar, RITMO envía el código EAN, UPC o GTIN a <a href="https://world.openfoodfacts.org" target="_blank" rel="noopener noreferrer" className="text-primary underline underline-offset-2">Open Food Facts</a> para recuperar los datos públicos del etiquetado. No se envían tu correo, tu historial ni la imagen de la cámara. La cámara procesa el código en el navegador cuando este permite hacerlo; RITMO no graba ni sube el vídeo. Open Food Facts es una base colaborativa, por lo que debes comparar los valores con el envase antes de guardar.</p></section>
      <section><h2>En este dispositivo</h2><p>RITMO conserva preferencias, cambios pendientes, copias locales y borradores para recuperarlos ante interrupciones. Los borradores de comidas dejan de recuperarse a los siete días. Evita usar una cuenta personal en dispositivos compartidos sin limpiar después los datos locales.</p></section>
      <section><h2>Diagnóstico opcional</h2><p>En Ajustes puedes autorizar el envío de tipos de errores, versión, ruta general, clase de dispositivo y métricas de carga. No se envían pesos, textos de comidas, notas, URL completa, correo ni grabaciones de pantalla. RITMO purga registros de más de 30 días cuando recibe nuevos diagnósticos; un contador por cuenta limita abusos y se renueva cada minuto. Los proveedores de alojamiento pueden conservar registros técnicos propios según su configuración.</p></section>
      <section><h2>Conservación y proveedores</h2><p>Los datos de la aplicación se conservan mientras mantengas tu cuenta o hasta que uses “Eliminar todos mis datos de RITMO”. Las copias operativas de Supabase y Vercel siguen sus propios periodos de seguridad y registro. Estos proveedores pueden tratar datos desde otros países con las garantías que describen en sus condiciones y políticas. RITMO no vende tus datos.</p></section>
      <section><h2>Exportar, limpiar y borrar</h2><p>Exportar descarga una copia de tus datos. Limpiar este dispositivo elimina las copias y preferencias locales de esta cuenta; no borra la nube. Eliminar los datos de RITMO borra los registros de la aplicación y sus copias en Storage, pero no elimina tu identidad de acceso ni las copias operativas del proveedor sujetas a su política de conservación.</p></section>
      <section><h2>Tus derechos</h2><p>Puedes exportar, corregir y eliminar los datos desde Ajustes. También puedes pedir acceso, rectificación, supresión, limitación, oposición o portabilidad al responsable, retirar el consentimiento sin afectar al tratamiento anterior y reclamar ante la Agencia Española de Protección de Datos. Para retirar el consentimiento de seguimiento desde la app, elimina tus datos de RITMO.</p></section>
      <section><h2>Una herramienta de seguimiento</h2><p>RITMO está dirigida a personas adultas. Las estimaciones nutricionales y de peso no son mediciones ni asesoramiento médico. No están destinadas a diagnosticar, tratar ni sustituir la atención de un profesional.</p></section>
    </div>
    <Link href="/ajustes" className="mt-6 inline-flex min-h-11 items-center text-sm font-semibold text-primary underline underline-offset-4">Abrir mis controles de privacidad</Link>
  </main>;
}
