import { test, expect } from "@playwright/test";
test("recorrido visual y guardado con datos sintéticos", async ({ page, request }, info) => {
  test.setTimeout(90000);
  const analisisRemotos: string[] = [];
  page.on("request", request => { if (request.url().includes("/api/nutricion") || /generativelanguage|api\.edamam/.test(request.url())) analisisRemotos.push(request.url()); });
  await request.post("http://127.0.0.1:3199/__reset");
  await page.goto("/login");
  await page.getByLabel("Email").fill("alex@ritmo.test");
  await page.getByLabel("Contraseña", { exact: true }).fill("RitmoTest123");
  await page.getByRole("button", { name: "Iniciar sesión", exact: true }).click();
  await expect(page).toHaveURL(/\/$/);
  await expect(page.getByText(/Buenas|Buenos/).first()).toBeVisible();
  await page.screenshot({ path: `test-results/${info.project.name}-hoy.png`, fullPage: true });
  for (const route of ["ajustes", "nutricion", "progreso", "habitos"]) {
    await page.goto(`/${route}`);
    await expect(page.locator("main h1").first()).toBeVisible();
    await expect(page.locator('main [data-slot="skeleton"]')).toHaveCount(0);
    await expect(page.getByText("Esta sección falló", { exact: true })).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    await page.screenshot({ path: `test-results/${info.project.name}-${route}.png`, fullPage: true });
  }
  await page.goto("/nutricion");
  await page.getByRole("button", { name: "Analizar otra comida" }).click();
  const prompt = page.getByRole("textbox", { name: "Descripción de la comida" });
  await prompt.fill("Ensalada con pollo y aceite de oliva");
  await page.getByRole("button", { name: "Analizar ingredientes", exact: true }).click();
  await expect(page.getByText("¿Cuánto aceite has usado en total?", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "10 ml", exact: true }).click();
  await page.getByRole("button", { name: "Analizar ingredientes", exact: true }).click();
  await expect(page.getByRole("button", { name: "Añadir a comida", exact: true })).toBeVisible();
  await page.screenshot({ path: `test-results/${info.project.name}-registro.png`, fullPage: true });
  await page.getByRole("button", { name: "Añadir a comida", exact: true }).click();
  await expect(page.getByText(/Comida añadida/).first()).toBeVisible();
  await page.getByText("Plan de comidas", { exact: true }).click();
  await page.getByLabel("Plato para planificar").selectOption({ index: 1 });
  await page.getByRole("button", { name: "Planificar", exact: true }).click();
  await expect(page.getByText(/· planificada/).first()).toBeVisible();
  await page.getByRole("button", { name: /Registrar .+ como consumida/ }).first().click();
  await expect(page.getByRole("button", { name: "Comida registrada", exact: true }).first()).toBeDisabled();
  await page.screenshot({ path: `test-results/${info.project.name}-plan.png`, fullPage: true });
  await page.goto("/");
  await page.getByRole("button", { name: "Preparar informe mensual" }).click();
  await expect(page.getByRole("switch", { name: "Evolución de peso" })).not.toBeChecked();
  await expect(page.getByRole("switch", { name: "Número de comidas" })).not.toBeChecked();
  await expect(page.getByRole("img", { name: /Vista previa de/ })).toBeVisible();
  await page.screenshot({ path: `test-results/${info.project.name}-informe.png`, fullPage: true });
  await page.getByRole("button", { name: "Close", exact: true }).click();
  await page.goto("/ajustes");
  await page.getByRole("button", { name: "Cerrar sesión", exact: true }).click();
  await expect(page).toHaveURL(/login/);
  await page.getByLabel("Email").fill("bea@ritmo.test");
  await page.getByLabel("Contraseña", { exact: true }).fill("RitmoTest123");
  await page.getByRole("button", { name: "Iniciar sesión", exact: true }).click();
  await expect(page.getByText(/Buenas tardes, Bea|Buenos días, Bea|Buenas noches, Bea/)).toBeVisible();
  await page.goto("/nutricion");
  await expect(page.getByText("Ensalada con pollo y aceite de oliva", { exact: false })).toHaveCount(0);
  expect(analisisRemotos).toEqual([]);
});
